"""sms_limit

Revision ID: 93d6643fc8dd
Revises: c2c763194c66
Create Date: 2024-02-04 14:07:32.069211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d6643fc8dd'
down_revision: Union[str, None] = 'c2c763194c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_ip_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_ip_limit_id'), 'sms_ip_limit', ['id'], unique=False)
    op.create_index(op.f('ix_sms_ip_limit_ip'), 'sms_ip_limit', ['ip'], unique=True)
    op.create_table('sms_phone_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_phone_limit_id'), 'sms_phone_limit', ['id'], unique=False)
    op.create_index(op.f('ix_sms_phone_limit_mobile'), 'sms_phone_limit', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_phone_limit_mobile'), table_name='sms_phone_limit')
    op.drop_index(op.f('ix_sms_phone_limit_id'), table_name='sms_phone_limit')
    op.drop_table('sms_phone_limit')
    op.drop_index(op.f('ix_sms_ip_limit_ip'), table_name='sms_ip_limit')
    op.drop_index(op.f('ix_sms_ip_limit_id'), table_name='sms_ip_limit')
    op.drop_table('sms_ip_limit')
    # ### end Alembic commands ###
