"""delete_table

Revision ID: a92d84752798
Revises: 93d6643fc8dd
Create Date: 2024-02-27 13:48:17.326355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a92d84752798'
down_revision: Union[str, None] = '93d6643fc8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sms_ip_limit_id', table_name='sms_ip_limit')
    op.drop_index('ix_sms_ip_limit_ip', table_name='sms_ip_limit')
    op.drop_table('sms_ip_limit')
    op.drop_index('ix_sms_phone_limit_id', table_name='sms_phone_limit')
    op.drop_index('ix_sms_phone_limit_mobile', table_name='sms_phone_limit')
    op.drop_table('sms_phone_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_phone_limit',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mobile', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sms_phone_limit_mobile', 'sms_phone_limit', ['mobile'], unique=True)
    op.create_index('ix_sms_phone_limit_id', 'sms_phone_limit', ['id'], unique=False)
    op.create_table('sms_ip_limit',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sms_ip_limit_ip', 'sms_ip_limit', ['ip'], unique=True)
    op.create_index('ix_sms_ip_limit_id', 'sms_ip_limit', ['id'], unique=False)
    # ### end Alembic commands ###
