"""alter_user_table_4

Revision ID: aaad3b24ff10
Revises: bebcf8b1bc32
Create Date: 2024-02-28 16:36:05.800704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaad3b24ff10'
down_revision: Union[str, None] = 'bebcf8b1bc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
