"""alter_user_table_3

Revision ID: bebcf8b1bc32
Revises: 963c093c17aa
Create Date: 2024-02-28 09:23:43.639251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bebcf8b1bc32'
down_revision: Union[str, None] = '963c093c17aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
